package io.soboro.supreme.core.model.user.exception

class NoAuthorizationException : RuntimeException("No authorization exception occurred")
