package io.soboro.supreme.core.model.user.exception

class UserNotFoundException: IllegalArgumentException("User not found")