package io.soboro.supreme.storage.db.core.entity.user.exception

class NoAuthorizationException : RuntimeException("No authorization exception occurred")
