package io.soboro.supreme.core.api.domain.user.exception

class NoAuthorizationException : RuntimeException("No authorization exception occurred")
